/* Generated By:JavaCC: Do not edit this line. BasicConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BasicConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int LBRACE = 9;
  /** RegularExpression Id. */
  int RBRACE = 10;
  /** RegularExpression Id. */
  int PRINT = 11;
  /** RegularExpression Id. */
  int IF = 12;
  /** RegularExpression Id. */
  int ELSE = 13;
  /** RegularExpression Id. */
  int INT = 14;
  /** RegularExpression Id. */
  int REAL = 15;
  /** RegularExpression Id. */
  int CONSTANT = 16;
  /** RegularExpression Id. */
  int IDENT = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;
  /** RegularExpression Id. */
  int LETTER = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"{\"",
    "\"}\"",
    "\"print\"",
    "\"if\"",
    "\"else\"",
    "\"int\"",
    "\"real\"",
    "<CONSTANT>",
    "<IDENT>",
    "<DIGIT>",
    "<LETTER>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
  };

}
