/* Generated By:JavaCC: Do not edit this line. BasicConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BasicConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int EQL = 9;
  /** RegularExpression Id. */
  int NEQ = 10;
  /** RegularExpression Id. */
  int LSS = 11;
  /** RegularExpression Id. */
  int GTR = 12;
  /** RegularExpression Id. */
  int LEQ = 13;
  /** RegularExpression Id. */
  int GEQ = 14;
  /** RegularExpression Id. */
  int LBRACE = 15;
  /** RegularExpression Id. */
  int RBRACE = 16;
  /** RegularExpression Id. */
  int PRINT = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int ELSE = 19;
  /** RegularExpression Id. */
  int INT = 20;
  /** RegularExpression Id. */
  int REAL = 21;
  /** RegularExpression Id. */
  int WHILE = 22;
  /** RegularExpression Id. */
  int CONSTANT = 23;
  /** RegularExpression Id. */
  int IDENT = 24;
  /** RegularExpression Id. */
  int DIGIT = 25;
  /** RegularExpression Id. */
  int LETTER = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"{\"",
    "\"}\"",
    "\"print\"",
    "\"if\"",
    "\"else\"",
    "\"int\"",
    "\"real\"",
    "\"while\"",
    "<CONSTANT>",
    "<IDENT>",
    "<DIGIT>",
    "<LETTER>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
  };

}
